---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pacificas.pacifica.github.io
spec:
  group: pacifica.github.io
  names:
    kind: Pacifica
    listKind: PacificaList
    plural: pacificas
    singular: pacifica
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
    - name: v1alpha1
      served: true
      storage: true
