---
dependency:
  name: galaxy
driver:
  name: docker
lint: yamllint . && ansible-lint
platforms:
  - name: kind-default
    groups:
      - k8s
    image: bsycorp/kind:latest-${KUBE_VERSION:-1.16}
    privileged: true
    override_command: false
    exposed_ports:
      - 8443/tcp
      - 10080/tcp
    published_ports:
      - 0.0.0.0:${TEST_CLUSTER_PORT:-9443}:8443/tcp
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      all:
        namespace: ${TEST_NAMESPACE:-osdk-test}
        kubeconfig_file: ${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
  env:
    K8S_AUTH_KUBECONFIG: ${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig
    KUBECONFIG: ${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
    KIND_PORT: '${TEST_CLUSTER_PORT:-9443}'
scenario:
  name: default
verifier:
  name: ansible
